<div>
  Error occured in account <%= @account.id %> :: <%= @account.full_domain %> while calculating the call charge for <%= @call_sid %>.
  <div><br></div>
  The exception is <%= @exception.message %> : 
  <div><br></div>
  <%= @exception.backtrace.first(5).join(":::") %>
</div>